视频响应的rights.is_stein_gate表示是否为互动视频
SocialSisterYi/bilibili-API-collect pull request #154
Opened 2021-02-08 08:46 UTC by DGCK81LNN

rt

表示互动视频的`attribute`掩码第29位&ZeroWidthSpace;_似乎_&ZeroWidthSpace;也已经废弃，API不再返回此值，故移除

2021-02-08 14:43 UTC, DGCK81LNN commented
@SocialSisterYi 艾特一下（？

2021-02-10 01:31 UTC, ProgramRipper requested changes

2021-02-10 01:31 UTC, ProgramRipper commented on video/info.md
> -| ~~attribute~~（仅做历史性保留） | ~~num~~ | ~~稿件属性位配置~~             | **详情见下表**<br />除互动视频外均已被删除且仅显示互动视频属性位 |
这里说的“做历史性保留”，应该是为了记录这个字段曾经的故事，即使它已毫无用处。
```suggestion
| ~~attribute~~（仅做历史性保留） | ~~num~~ | ~~稿件属性位配置~~             | **详情见下表**|
 ```

2021-02-11 01:19 UTC, DGCK81LNN commented
重新添加了attributes，并注明已弃用

2021-02-11 03:10 UTC, merged