添加部分查询动态的api解析
SocialSisterYi/bilibili-API-collect pull request #36
Opened 2020-08-01 07:26 UTC by dangjinghao

动态返回的信息可太多了，就解析了一部分，后面慢慢来吧

2021-02-08 09:24 UTC, DGCK81LNN requested changes
我之前研究过关于动态的API（开发者工具F12 Network面板抓的），每种不同的动态类型的card格式都是完全不同的，所以最好还是先判断type的值再去解析card。参考#143。

2021-02-08 09:24 UTC, DGCK81LNN commented on dynamic/user.md
> +| videos         | num  | 视频数？               | 视频类动态存在                 |
这样可太乱了，谁受得了（

所以说建议把不同类型的动态card分开处理

2021-02-08 09:24 UTC, DGCK81LNN commented on dynamic/user.md
> +| type           | num  | 动态类型             | **暂时无法确定**                     |
动态类型参考#143，这个还是要稍微确定一下的

2021-02-08 09:39 UTC, DGCK81LNN commented on dynamic/user.md
> +|                |      |                      |                                      |
```suggestion
| 字段           | 类型 | 内容                 | 备注                                 |
| -------------- | ---- | -------------------- | ------------------------------------ |
| uid            | num  | 发送动态用户uid      |                                      |
| type           | num  | 动态类型             | 参见下表                             |
| dynamic_id     | num  | 本动态id             |                                      |
| dynamic_id_str | str  | 本动态id字符串       |                                      |
| rid            | num  | 视频av号             | 视频类动态和转发视频动态存在         |
| rid_str        | str  | av号字符串           | 视频类动态和转发视频动态存在         |
| bvid           | str  | bv号                 | 视频类动态和转发视频动态存在         |
| acl            | num  |                      | **暂时无法确定**                     |
| view           | num  | 动态阅读数           | 暂时不知道如何增加计数               |
| repost         | num  | 转发数               |                                      |
| comment        | num  | 评论数               |                                      |
| is_like        | num  | 0/1                  | 自己用户是否赞了该动态               |
| timestamp      | num  | 动态发送时间的时间戳 |                                      |
| origin         | obj  | 最初的动态相关信息   | 转发动态时存在                       |
| orig_type      | num  | 最初的动态类型       | 非转发动态为0                        |
| orig_dy_id     | num  | 最初的动态id         | 非转发动态为0                        |
| orig_dy_id_str | str  | 最初的动态id字符串   | 非转发动态为0                        |
| previous       | obj  | 转发的动态相关信息   | 连环转发时存在                       |
| pre_dy_id      | num  | 转发的动态id         | 非转发动态为0                        |
| pre_dy_id_str  | str  | 转发的动态id字符串   | 非转发动态为0                        |
| user_profile   | obj  | 用户信息             |                                      |
| uid_type       | num  |                      | **暂时无法确定**                     |
| stype          | num  |                      | **暂时无法确定**                     |
| r_type         | num  |                      | **暂时无法确定**                     |
| inner_id       | num  |                      | **暂时无法确定**                     |
| status         | num  |                      | **暂时无法确定**                     |
```

2022-10-24 07:42 UTC, SocialSisterYi commented
才发现还有个上古时期的PR，现在都改冲突了，关了吧

2022-10-24 07:42 UTC, closed without merging