feature: App Sign 添加java版本实现
SocialSisterYi/bilibili-API-collect pull request #729
Opened 2023-07-01 03:50 UTC by cctyl

App Sign 添加java版本实现

2023-07-01 11:20 UTC, xiaoyv404 requested changes

2023-07-01 11:20 UTC, xiaoyv404 commented on docs/misc/sign/APP.md
> +        return generateMD5(queryBuilder.toString() + APP_SEC);
`.toString()` method is unnecessary

2023-07-01 11:36 UTC, xiaoyv404 requested changes

2023-07-01 11:36 UTC, xiaoyv404 commented on docs/misc/sign/APP.md
> +该 Demo 提供 [Python](#Python)  [Java](#Java) 语言例程
请使用 `和` 连接

2023-07-02 01:08 UTC, cctyl commented on docs/misc/sign/APP.md
> +该 Demo 提供 [Python](#Python)  [Java](#Java) 语言例程
这个是我需要修改后，重新提交。还是直接点击resolve conversation

2023-07-02 01:12 UTC, xiaoyv404 commented on docs/misc/sign/APP.md
> +该 Demo 提供 [Python](#Python)  [Java](#Java) 语言例程
提交，然后[重新请求审核](https://docs.github.com/zh/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews#re-requesting-a-review)

2023-07-02 01:44 UTC, xiaoyv404 approved these changes

2023-07-02 01:44 UTC, merged