:sparkles: feat(直播间管理 API): 添加更新公告与标签 API
SocialSisterYi/bilibili-API-collect pull request #752
Opened 2023-07-23 07:37 UTC by NoahCodeGG

2023-07-24 02:30 UTC, xiaoyv404 requested changes

2023-07-24 02:30 UTC, xiaoyv404 commented on docs/live/manage.md
> -| message | str    | 错误信息 | 默认为ok                                               |
减少不必要的更改

2023-07-24 02:30 UTC, xiaoyv404 commented on docs/live/manage.md
> -| data    | obj  | 信息本体 |                                                              |
减少不必要的更改

2023-07-24 02:30 UTC, xiaoyv404 commented on docs/live/manage.md
> -| ------- | ---- | -------- | ------------------------------------------------------------ |
减少不必要的更改

2023-07-24 02:30 UTC, xiaoyv404 commented on docs/live/manage.md
> -| 0    | obj  | ？？？ | 作用尚不明确 |
减少不必要的更改

2023-07-25 02:09 UTC, xiaoyv404 approved these changes

2023-07-25 02:09 UTC, xiaoyv404 approved these changes

2023-07-25 02:11 UTC, SocialSisterYi approved these changes

2023-07-25 02:12 UTC, merged