移除多余转义符
SocialSisterYi/bilibili-API-collect pull request #777
Opened 2023-08-08 12:25 UTC by 188102836

移除此处多余的转义符
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/69347367/d4c2c1f8-b0a9-43e2-a9bf-b194afa9712b)

2023-08-09 17:37 UTC, catlair commented
从最开始的优化变成了骚操作😂

提供一个骚操作

```js
mixinKeyEncTab.map(n => orig[n])
    .join('')
    .slice(0, 32);
```

2023-08-10 04:38 UTC, catlair commented
这里有个很奇怪的东西 `temp.slice(0, 32)` 这是毫无意义的一个步骤，我们只需要让 mixinKeyEncTab  的长度为 32 即可，因为遍历的是 mixinKeyEncTab ，32 位之后的本来就会被抛弃，干嘛还让他们参与计算

```js
function getMixinKey(orig) {
  return [
    46, 47, 18, 2, 53, 8, 23, 32, 15, 50, 10, 31, 58, 3, 45, 35, 27, 43, 5, 49, 33, 9, 42, 19, 29,
    28, 14, 39, 12, 38, 41, 13,
  ].reduce((acc, cur) => acc + orig[cur], '');
}
```

2023-08-10 04:49 UTC, catlair commented
> 这里有个很奇怪的东西 `temp.slice(0, 32)` 这是毫无意义的一个步骤，我们只需要让 mixinKeyEncTab 的长度为 32 即可，因为遍历的是 mixinKeyEncTab ，32 位之后的本来就会被抛弃，干嘛还让他们参与计算
> 
> ```js
> function getMixinKey(orig) {
>   return [
>     46, 47, 18, 2, 53, 8, 23, 32, 15, 50, 10, 31, 58, 3, 45, 35, 27, 43, 5, 49, 33, 9, 42, 19, 29,
>     28, 14, 39, 12, 38, 41, 13,
>   ].reduce((acc, cur) => acc + orig[cur], '');
> }
> ```

b 站程序员是一个比一个鬼才

2023-08-10 08:17 UTC, 0f-0b requested changes

2023-08-10 08:17 UTC, 0f-0b commented on docs/misc/sign/wbi.md
> +            )
`encodeURIComponent("=") !== "="`。

```suggestion
            `${encodeURIComponent(key)}=${encodeURIComponent(
                // 过滤 value 中的 "!'()*" 字符
                params[key].toString().replace(chr_filter, '')
            )}`
```

2023-08-10 08:17 UTC, 0f-0b commented on docs/misc/sign/wbi.md
> +getWbiKeys().then((wbi_keys) => {
为何避免 `await`？

2023-08-10 09:56 UTC, catlair commented on docs/misc/sign/wbi.md
> +getWbiKeys().then((wbi_keys) => {
> 为何避免 `await`？

应该是避免顶层 await 。顶层await需要作用于ESM。这可能会导致很多对js不了解的人产生疑问

2023-08-10 10:04 UTC, catlair commented on docs/misc/sign/wbi.md
> +getWbiKeys().then((wbi_keys) => {
不过没有任何影响，不会有人看到这还不知道怎么用promise

2023-08-10 10:41 UTC, 188102836 commented on docs/misc/sign/wbi.md
> +getWbiKeys().then((wbi_keys) => {
是的，CommonJS模块不支持顶层 `await`

2023-08-13 12:29 UTC, 0f-0b approved these changes

2023-08-13 12:31 UTC, xiaoyv404 approved these changes

2023-08-13 12:31 UTC, merged