[API修改] 风纪委员会获取案件信息 close #598
SocialSisterYi/bilibili-API-collect pull request #782
Opened 2023-08-13 02:17 UTC by catlair

2023-08-13 08:03 UTC, xiaoyv404 commented
please write "close #598" in description

2023-08-13 08:05 UTC, xiaoyv404 requested changes

2023-08-13 08:05 UTC, xiaoyv404 commented on docs/blackroom/jury/judgement_info.md
> +| vote_info    | object | 投票信息                         |                                                                |
减少无用更改

2023-08-13 08:05 UTC, xiaoyv404 commented on docs/blackroom/jury/judgement_info.md
> +| comments     | object | 若干条评论   | 仅当`case_type`为`2`有值。见「对象：评论信息」  |
减少无用更改

2023-08-13 08:05 UTC, xiaoyv404 commented on docs/blackroom/jury/judgement_info.md
> +| content        | str    | 评论内容                 |                                                                |
减少无用更改

2023-08-13 11:20 UTC, catlair commented on docs/blackroom/jury/judgement_info.md
> +| content        | str    | 评论内容                 |                                                                |
> 减少无用更改

 他这些表格之前都没有空格，全部在一堆，我认为有必要格式化。

2023-08-13 11:39 UTC, xiaoyv404 commented on docs/blackroom/jury/judgement_info.md
> +| content        | str    | 评论内容                 |                                                                |
@SocialSisterYi 易姐姐觉得呢

2023-08-14 04:41 UTC, SocialSisterYi commented on docs/blackroom/jury/judgement_info.md
> +| content        | str    | 评论内容                 |                                                                |
这个没问题啊，就是 md 文本层面上的对齐，typora 之类的现代编辑器都可以自动完成这个步骤

2023-08-14 04:42 UTC, xiaoyv404 approved these changes

2023-08-14 04:44 UTC, merged